### PR TITLE
Fix bug - Locked vehicle on death & perma locked vehicle

### LINKED ISSUE #2296: Vehicle locked bug
**When going into a vehicle and switching to any passenger seat insead of driver seat, then locking and leaving the vehicle will make it locked forever until server restart.**

1. Get into a vehicle;
2. CTRL + 2/3/4/5 (switch seat to passenger);
3. Press TAB and click on the lock icon;
4. Exit and press E to leave the vehicle;
5. The vehicle is now stuck on locked and can't be accessed anymore by anyone.

**When going into a vehicle and locking the vehicle, then die. The vehicle will stay locked untill the player that got killed is respawned.**

1. Get into a vehicle;
2. Press TAB and click on the lock icon;
3. Get killed by someone outside of the vehicle;
4. The vehicle is now stuck on locked and can't be accessed anymore by anyone;
5. Respawn and the vehicle is now accessible again.

### PR DESCRIPTION
**Pull request by GumpyH1Z1**
Fixed the issue where a vehicle would stay locked, when a player, which had locked the vehicle, would die and not respawn.

Fixes #2296

### CODE REVIEW

**Comment by GumpyH1Z1** [comment]
Tested and works for me. Tried out all seating positions.

**Comment by Nikolassparrow** [comment]
This doesn't work btw. I saw your video in the discord, doing /respawn is completely different than when a player actually kills you.

That's where the bug occurs, is when a player kills another inside of the vehicle which causes the perma-locked car.

**Comment by GumpyH1Z1** [comment]
> This doesn't work btw. I saw your video in the discord, doing /respawn is completely different than when a player actually kills you.
> 
> That's where the bug occurs, is when a player kills another inside of the vehicle which causes the perma-locked car.

That was with the old code. I’ve been testing with 2 different instances of the game. If I have time tommorow I will make a new video for you. The perma-locked car is a whole different bug and has nothing to do with dieing.

**Comment by Nikolassparrow** [comment]
> > This doesn't work btw. I saw your video in the discord, doing /respawn is completely different than when a player actually kills you.
> > That's where the bug occurs, is when a player kills another inside of the vehicle which causes the perma-locked car.
> 
> That was with the old code. I’ve been testing with 2 different instances of the game. If I have time tommorow I will make a new video for you. The perma-locked car is a whole different bug and has nothing to do with dieing.
> 
> Or see for yourself and launch a server with this code.

I did test your code, it didn't work lol.

**Comment by GumpyH1Z1** [comment]
> > > This doesn't work btw. I saw your video in the discord, doing /respawn is completely different than when a player actually kills you.
> > > That's where the bug occurs, is when a player kills another inside of the vehicle which causes the perma-locked car.
> > 
> > 
> > That was with the old code. I’ve been testing with 2 different instances of the game. If I have time tommorow I will make a new video for you. The perma-locked car is a whole different bug and has nothing to do with dieing.
> > Or see for yourself and launch a server with this code.
> 
> I did test your code, it didn't work lol.

I will send you a video tommorow.

**Comment by Nikolassparrow** [comment]
> I will send you a video tommorow.

No need, #2300 fixes this bug without overcomplicating it + it actually works as this PR doesnt.. lol

**Comment by QuentinGruber** [comment]
Lmao don't fight I will test both tomorrow and pick one

**Comment by GumpyH1Z1** [comment]
> Lmao don't fight I will test both tomorrow and pick one

I didn’t see it as fighting, but good feedback. Maybe a channel to discuss stuff like this would be great.

**Comment by GumpyH1Z1** [comment]
https://www.youtube.com/watch?v=NQEN8znjpLM

The video shows me testing the fix for both bugs.

File: src/servers/ZoneServer2016/zoneserver.ts [hunk 1]
```diff
@@ -2481,13 +2481,29 @@ export class ZoneServer2016 extends EventEmitter {
...
         };
       }
+    
+      // Check if character is dead
+      if (!client.character.isAlive) {
+        // Wait untill killCharacter is finished for dismountVehicle (if not, there will be no option for the dead occupant to respawn)
+        this.once("killCharacterComplete", (client) => {
+          this.dismountVehicle(client);
+
+          if (occupantsCount > 1 && lockedState) {
```
Comment (QuentinGruber) [inline src/servers/ZoneServer2016/zoneserver.ts:2501]: I'm wondering since occupantsCount is copied prior dismount, currently since all of this func and its calls are synchronous it create no issues, but if at some point we change that, we might have an issue there, so maybe get that data directly it the event. Using an event is a good idea, i would have used a microtask but yeah if we change anything to async it would have create issue. Tell me what you think :)


```
Welcome to Node.js v23.3.0.
Type ".help" for more information.
> const arr = [1,1]
undefined
> arr.length
2
> const b = arr.length
undefined
> arr.push(1)
3
> arr.length
3
> b
2
> 
```

Comment (QuentinGruber) [reply src/servers/ZoneServer2016/zoneserver.ts:2501]: also it's kinda the same for the locking state

**Review by QuentinGruber — CHANGES_REQUESTED** [review]

File: src/servers/ZoneServer2016/zoneserver.ts (hunk 1 above)
Comment (GumpyH1Z1) [reply src/servers/ZoneServer2016/zoneserver.ts:2501]: > @GumpyH1Z1 since you're working on a fork i can't do these changes myself btw

Let me push these changes into a branch of your repo.

Comment (QuentinGruber) [reply src/servers/ZoneServer2016/zoneserver.ts:2510]: @GumpyH1Z1  you can push to your branch tho just updt this pr 🤠

**Review by QuentinGruber — APPROVED** [review]
